apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints  # Scraping the Kubernetes API Server

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node  # Scraping Node-level metrics

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod  # Scraping Pod-level metrics
